= 2015 the year ahead
:hp-tags: year plan, tech, books
:published_at: 2015-29-01

Last year was full of change, I got engaged(!), refocused on client side development, worked in an (proper) agile scrum team for the first time, attended my first meetup, architected a custom adaptive framework using SCSS, and finally, left my job at the very end of the year to chase new challenges.

This year I've joined JustEat as a software engineer which involves heavy use of API's and internationalisation, whilst striving for high availability and scalability; all areas I am keen to learn more about. I'm excited to be working for such a large technology driven company with an awesome culture, and loads of experienced engineers to learn from. Plus my podcast obesession has increased thanks to the extra commute time!

This means my focus is moving back to the server side again, but I plan to keep a healthy mix of both client & server side.

Because so much has been changing recently I wanted to write down a few things to focus on over the next 12 months. 


### Tech

A lot of my time is spent reading about web frameworks and languages, but I rarely take the time to dive in and try them out in any depth. That will change this year. 

My first target this year will be EcmaScript 6 which I feel that I've put off for long enough. This will be followed by Angular or possibly [Rob Eisenberg's new framework Aurelia](http://aurelia.io/) which looks very interesting.

As a result of this my plan is to record my experiences here and hopefully have a few projects up on GitHub.


### Books

I'm aiming to read one book a month. No more, no less, I don't want to stretch myself or be unrealisitic. If it's a technical book and I feel the urge, I'll put some code up on [my GitHub profile](http://github.com/DJMelonz), and write a review here.

These are my books of choice, in no particular order

* Git in practice
* Release it!
* JavaScript application design
* Secrets of the JavaScript ninja
* The responsive web
* Soft skills
* Head first design patterns
* Dependency injection in .Net
* C# in depth
* Seven Languages in Seven Weeks (envisage this being a 2 month read)
* ReWork: Change the Way You Work Forever

One of the benefits of working for JustEat is a free subscription to [Safari](https://www.safaribooksonline.com/) which means I have access to most of the books in the list.

### Blog

I'm not going to make any crazy commitments such as posting here every week, but I'm planning on writing about anything I find really interesting instead of keeping it all in my head. Hopefully I can look back at these posts for future reference, and who knows maybe somebody else will find them useful. 

Good luck future me!
